import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PUC Minas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-slate-300 p-3">
          <nav>
            <ul className="flex items-center">
              <li className="me-4 text-xl">
                <Link href={"/"}>
                  <h1>Puc minas</h1>
                </Link>
              </li>
              <li className="me-4 hover:font-bold">
                <Link href={"/login"}>Login</Link>
              </li>
              <li className=" hover:font-bold">
                <Link href={"/create"}>Create a new user</Link>
              </li>
            </ul>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
